### ISSUE TITLE
React Webpack Boilerplate v.2

### ISSUE THREAD

**Issue by KleoPetroff** [KleoPetroff/react-webpack-boilerplate#4]
React Webpack Boilerplate v.2 will introduce some long needed features and optimizations. All new commits will be done to the [v.2 branch](https://github.com/KleoPetroff/react-webpack-boilerplate/tree/v.2), leaving the master branch intact and ready for use as it is.

- [x] Implement unit tests (#9)
- [x] CI and badges (#10 and #11)
- [x] Git pre-commit hook (#27)
- [x] Issue templates
- [x] Improve documentation

The dependencies will be updated on both v.2 and master branches.

**Comment by KleoPetroff** [comment]
All milestone changes are implemented and merged to master. Happy v.2 !! :tada: :star: :tada:
